trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: RunningMyTestScript
  jobs:
  - job: RunTests
    steps:
    - task: UseJavaVersion@0
      inputs:
        versionSpec: '11'

    - script: echo Hello, Bhai jaan !!!
      displayName: 'Hello Ji !!!'
