jobs:
- deployment: Deploy
  displayName: 'Deploy Stage'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'src/Test/Scripts/Conventional/CAO/CentralizedClearing/CentralizedClearing.java'